import 'dart:async';
import 'dart:io' show File;
import 'dart:typed_data' show Uint8List;

import 'package:dio/dio.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:uuid/uuid.dart';

import '../../core/chat_client.dart';
import '../../core/chat_client_provider.dart';
import '../../core/files_providers.dart';
import '../../core/network_banner.dart';
import '../../features/vision/vision_client.dart';
import '../../features/vision/vision_provider.dart';
import '../attachments/file_model.dart';
import '../attachments/file_store.dart';
import '../attachments/upload_queue.dart';
import 'chat_store.dart';
import 'context_trimmer.dart';
import 'database_providers.dart';
import 'message_model.dart';
import 'tool_executor.dart';

/// Snapshot of a single conversation's chat state, consumed by the UI.
class ConversationState {
  final List<Message> messages;
  final bool isStreaming;
  final String? error;

  /// Id of the last user message still awaiting a reply (drives the
  /// typing indicator / disabled input).
  final String? pendingUserMessageId;

  /// Id of the assistant placeholder that errored (drives the retry UI).
  final String? failedMessageId;

  /// True once the conversation has been loaded from the store.
  final bool isDbReady;

  /// Live upload progress for attachment jobs, keyed by job id. A `done`
  /// status carries the server file id; a `failed` status carries an error.
  /// Updated as the upload queue reports progress.
  final Map<String, UploadJobStatus> attachmentUploads;

  const ConversationState({
    required this.messages,
    this.isStreaming = false,
    this.error,
    this.pendingUserMessageId,
    this.failedMessageId,
    this.isDbReady = false,
    this.attachmentUploads = const {},
  });

  ConversationState copyWith({
    List<Message>? messages,
    bool? isStreaming,
    Object? error = _sentinel,
    Object? pendingUserMessageId = _sentinel,
    Object? failedMessageId = _sentinel,
    Object? attachmentUploads = _sentinel,
    bool? isDbReady,
  }) {
    return ConversationState(
      messages: messages ?? this.messages,
      isStreaming: isStreaming ?? this.isStreaming,
      error: identical(error, _sentinel) ? this.error : error as String?,
      pendingUserMessageId: identical(pendingUserMessageId, _sentinel)
          ? this.pendingUserMessageId
          : pendingUserMessageId as String?,
      failedMessageId: identical(failedMessageId, _sentinel)
          ? this.failedMessageId
          : failedMessageId as String?,
      attachmentUploads: identical(attachmentUploads, _sentinel)
          ? this.attachmentUploads
          : attachmentUploads as Map<String, UploadJobStatus>,
      isDbReady: isDbReady ?? this.isDbReady,
    );
  }
}

const Object _sentinel = Object();

const kSystemPrompt =
    'You are a helpful voice assistant running on the user\'s self-hosted home AI stack. Be concise in casual chat but thorough when asked. You can call tools when they help. If a tool fails, say so plainly and offer alternatives. '
    'The user may attach files to their messages. When you see [Image: ...] text, that is a text description of an attached image generated by a vision model. You may reference the image content based on the description. File references like [file:abc123] may also appear after upload completion — you do not need to describe images referenced this way.';

/// Drives the chat UI for a single conversation, streaming LLM completions and
/// executing tools. Riverpod 3 family notifier; the conversation id is passed
/// via the constructor from the provider's create function.
class ConversationNotifier extends AsyncNotifier<ConversationState> {
  ConversationNotifier(this.conversationId);

  final String conversationId;

  final _uuid = const Uuid();

  /// Cancel token for the in-flight request.
  CancelToken? _active;

  /// Text of the most recent user message, kept for retry().
  String? _lastUserText;

  /// Cancellation state of the in-flight turn is derived from the active
  /// [CancelToken] (see [stop] / [_onError]) rather than a bare bool, so a
  /// stale cancellation from a previous (stopped) turn can never be
  /// mis-attributed to a newer turn that is running fine.

  /// Coalesces streamed content deltas into ~80ms batched state updates.
  Timer? _throttle;
  String? _pendingAssistantId;
  StringBuffer? _pendingContent;

  ChatStore? _store;
  ChatClient? _client;
  ContextTrimmer? _trimmer;
  ToolRegistry? _registry;
  FileStore? _fileStore;

  /// Owned by this notifier and disposed with it (§3.3). Created in [build]
  /// from [filesServiceProvider]; a [NoOpFilesClient] (no files secret
  /// configured) fails uploads gracefully with a clear error.
  UploadQueue? _queue;

  /// Maps an upload job id to the user message it belongs to, so a completed
  /// upload's `[file:<id>]` reference is appended to the right message.
  final Map<String, String> _jobUserMessageId = {};

  /// Upload job ids whose `[file:<id>]` reference has already been appended.
  final Set<String> _appendedRefs = {};

  /// Serializes [FileInfo] + message persistence across concurrently-completing
  /// uploads. Without it, two jobs finishing back-to-back each write the full
  /// user message and the later write can clobber the earlier ref.
  Future<void> _persistChain = Future.value();

  @override
  Future<ConversationState> build() async {
    _store = ref.watch(chatStoreProvider);
    // Read (not watch) the settings-dependent providers: both
    // chatApiClientProvider and filesServiceProvider rebuild when the user
    // saves settings, and re-running build() would dispose the UploadQueue
    // owned here — silently cancelling any in-flight upload and losing the
    // `[file:<id>]` ref. The client instances are snapshot at build time and
    // stay pinned to this conversation's lifetime.
    _client = ref.read(chatApiClientProvider);
    _trimmer = ref.watch(contextTrimmerProvider);
    _registry = ref.watch(toolRegistryProvider);
    _fileStore = ref.watch(filesStoreProvider);
    final queue = UploadQueue(filesService: ref.read(filesServiceProvider));
    _queue = queue;

    // Wait for the database to be ready before loading messages.
    await ref.watch(databaseReadyProvider);
    if (!ref.mounted) return const ConversationState(messages: []);

    queue.jobs.addListener(_onQueueChanged);

    ref.onDispose(() {
      queue.jobs.removeListener(_onQueueChanged);
      queue.dispose();
      _active?.cancel();
      _throttle?.cancel();
    });

    final conversation = await _store!.loadConversation(conversationId);
    if (!ref.mounted) return const ConversationState(messages: []);

    return ConversationState(
      messages: conversation?.messages ?? const [],
      isDbReady: true,
    );
  }

  Future<void> sendMessage(
    String text, {
    List<AttachmentDraft> attachments = const [],
  }) async {
    final current = state.value;
    if (current == null || current.isStreaming) return;

    final trimmed = text.trim();
    if (trimmed.isEmpty) return;

    _lastUserText = trimmed;

    final userMsg = Message(
      id: _uuid.v4(),
      role: MessageRole.user,
      content: trimmed,
      createdAt: DateTime.now(),
    );

    _setState(current.copyWith(
      messages: [...current.messages, userMsg],
      pendingUserMessageId: userMsg.id,
      isStreaming: true,
      error: null,
      failedMessageId: null,
    ));

    // Brand-new conversations need their row created first (the message row's
    // FK references it), with a title derived from the first user message.
    final existing = await _store!.loadConversation(conversationId);
    if (!ref.mounted) return;

    if (existing == null) {
      final title = trimmed.length <= 60
          ? trimmed
          : '${trimmed.substring(0, 60)}…';
      await _store!.saveConversation(Conversation(
        id: conversationId,
        title: title,
        messages: [userMsg],
        createdAt: userMsg.createdAt ?? DateTime.now(),
        updatedAt: DateTime.now(),
      ));
    } else {
      await _store!.appendMessage(conversationId, userMsg);
    }
    if (!ref.mounted) return;

    // Pre-send describe: attach image descriptions so the current turn
    // benefits from vision. Fail-open on failure — never blocks the send.
    if (attachments.isNotEmpty) {
      final visionEnabled = ref.read(visionEnabledProvider) ?? true;
      if (visionEnabled) {
        final descriptions = await _describeDrafts(attachments);
        if (descriptions.isNotEmpty) {
          final expanded = _injectImageDescriptions(userMsg.content, descriptions);
          final updatedUserMsg = userMsg.copyWith(content: expanded);
          final cur = state.value!;
          final updatedMessages = [
            for (final m in cur.messages)
              if (m.id == updatedUserMsg.id) updatedUserMsg else m,
          ];
          _setState(cur.copyWith(messages: updatedMessages));
          await _store!.updateMessage(conversationId, updatedUserMsg);
        }
      }
    }

    try {
      await _runTurn();
    } catch (_) {
      // A failed turn must NOT enqueue attachments: the UI retains the
      // selection (chat_screen._send does not clear it on failure), so a
      // retry re-sends exactly once instead of uploading the same files
      // twice. Note: a *chat* error (network/tool) is handled inside
      // _streamOnce/_onError and does not throw here, so uploads still start
      // for a turn whose reply failed but whose message was persisted.
      //
      // An unexpected throw leaves the streaming flag set (only the success
      // path / _onError clears it), which would wedge the conversation: the
      // input stays disabled and the user could never retry. Clear it here so
      // the UI is usable again, while still rethrowing so _send keeps the
      // text + attachment selection intact.
      final cur = state.value;
      if (cur != null && ref.mounted) {
        _setState(cur.copyWith(
          isStreaming: false,
          pendingUserMessageId: null,
        ));
      }
      rethrow;
    }
    // §3.6: attachments upload asynchronously AFTER the turn succeeds, so the
    // user's text is never blocked on slow uploads.
    _enqueueAttachments(attachments, userMsg.id);
  }

  void _enqueueAttachments(List<AttachmentDraft> attachments, String userMsgId) {
    final queue = _queue;
    if (queue == null || attachments.isEmpty) return;
    for (final draft in attachments) {
      unawaited(_enqueueOne(queue, draft, userMsgId));
    }
  }

  Future<void> _enqueueOne(
    UploadQueue queue,
    AttachmentDraft draft,
    String userMsgId,
  ) async {
    try {
      final jobId = await queue.enqueue(
        path: draft.path,
        filename: draft.filename,
        sizeBytes: draft.sizeBytes,
        mimeType: draft.mimeType,
      );
      _jobUserMessageId[jobId] = userMsgId;
      // The upload may have already completed by the time the mapping above is
      // recorded (an already-resolved service completes in a microtask);
      // reconcile any such job now so its [file:<id>] ref is not dropped.
      final jobs = queue.jobs.value;
      if (jobs.any((j) => j.id == jobId && j.status == UploadStatus.done)) {
        _handleCompletedJobs(jobs);
      }
    } catch (_) {
      // Best-effort: a failed enqueue leaves no job to surface in state.
    }
  }

  /// Mirrors the queue's live jobs into [ConversationState.attachmentUploads]
  /// and, for newly-completed uploads, appends the `[file:<id>]` reference to
  /// the owning user message (in-memory + persisted).
  void _onQueueChanged() {
    if (!ref.mounted) return;
    final current = state.value;
    if (current == null) return;

    final jobs = _queue?.jobs.value ?? const <UploadJob>[];
    final uploads = <String, UploadJobStatus>{};
    for (final job in jobs) {
      uploads[job.id] = UploadJobStatus(
        jobId: job.id,
        status: job.status,
        progress: job.progress,
        error: job.error,
        serverFileId: job.serverFileId,
        uri: job.uri,
      );
    }
    _setState(current.copyWith(attachmentUploads: uploads));
    _handleCompletedJobs(jobs);
  }

  void _handleCompletedJobs(List<UploadJob> jobs) {
    for (final job in jobs) {
      final serverFileId = job.serverFileId;
      if (job.status != UploadStatus.done || serverFileId == null) continue;
      // The jobId -> user message mapping is recorded a microtask after the
      // job is enqueued; a very fast upload may finish first. Skip without
      // marking the ref appended so [_enqueueOne]'s reconciliation can retry.
      final userMsgId = _jobUserMessageId[job.id];
      if (userMsgId == null) continue;
      if (!_appendedRefs.add(job.id)) continue;

      final cur = state.value;
      if (cur == null) continue;
      Message? updated;
      for (final m in cur.messages) {
        if (m.id == userMsgId) {
          updated = m.copyWith(content: _appendFileRef(m.content, serverFileId));
          break;
        }
      }
      if (updated == null) continue;

      _setState(cur.copyWith(messages: [
        for (final m in cur.messages)
          if (m.id == userMsgId) updated else m,
      ]));
      // Serialize persistence in completion order so two uploads finishing
      // concurrently can't overwrite each other's [file:<id>] ref in the DB.
      _persistChain = _persistChain.then(
        (_) => _persistCompletedUpload(job, serverFileId, userMsgId),
      );
    }
  }

  /// Appends `[file:<id>]` to a user message's content (idempotent per id).
  String _appendFileRef(String content, String fileId) {
    final ref = '[file:$fileId]';
    if (content.contains(ref)) return content;
    return content.isEmpty ? ref : '$content $ref';
  }

  Future<void> _persistCompletedUpload(
    UploadJob job,
    String serverFileId,
    String userMsgId,
  ) async {
    if (!ref.mounted) return;
    try {
      // Re-read the freshest in-memory content (every ref appended so far) so
      // the write is consistent even if another upload completed meanwhile.
      final message = _latestUserMessage(userMsgId);
      if (message != null) {
        await _store!.updateMessage(conversationId, message);
      }
    } catch (_) {
      // Best-effort: the reference is already reflected in in-memory state.
    }
    if (!ref.mounted) return;
    try {
      await _fileStore!.saveFile(
        FileInfo(
          id: serverFileId,
          filename: job.filename,
          sizeBytes: job.sizeBytes,
          mimeType: job.mimeType,
          uploadedAt: DateTime.now(),
        ),
        conversationId: conversationId,
      );
    } catch (_) {
      // Best-effort: a persistence failure must not crash the turn.
    }
  }

  /// Returns the current in-memory user message for [userMsgId], or null.
  Message? _latestUserMessage(String userMsgId) {
    final cur = state.value;
    if (cur == null) return null;
    for (final m in cur.messages) {
      if (m.id == userMsgId) return m;
    }
    return null;
  }

  /// Resolves a description for each local draft in parallel, with a 5s
  /// timeout per image. Fail-open: failures/timeouts skip that image.
  Future<Map<String, String>> _describeDrafts(
    List<AttachmentDraft> attachments,
  ) async {
    final visionAsync = ref.read(visionClientProvider);
    final client = visionAsync.maybeWhen(
      data: (c) => c,
      orElse: () => const NoOpVisionClient(),
    );
    final descriptions = <String, String>{};
    final futures = attachments.map((draft) async {
      final bytes = await _readDraftBytes(draft.path);
      if (bytes == null) return;
      try {
        final description = await client
            .describeImage(
              bytes: bytes,
              mimeType: draft.mimeType,
            )
            .timeout(const Duration(seconds: 5));
        if (description.trim().isNotEmpty) {
          descriptions[draft.filename] = description;
        }
      } catch (e) {
        if (e is Error || e is Exception) {
          // Fail-open: skip this image.
        } else {
          rethrow;  // Preserve fatal errors
        }
      }
    });
    await Future.wait(futures);
    return descriptions;
  }

  Future<Uint8List?> _readDraftBytes(String path) async {
    try {
      final file = File(path);
      if (await file.exists()) {
        return await file
            .readAsBytes()
            .timeout(const Duration(seconds: 5));
      }
    } catch (_) {
      return null;
    }
    return null;
  }

  String _injectImageDescriptions(
    String content,
    Map<String, String> descriptions,
  ) {
    var result = content;
    for (final entry in descriptions.entries) {
      final block = '[Image: ${entry.value}]';
      result = result.isEmpty ? block : '$result\n$block';
    }
    return result;
  }

  /// Reads descriptions from the DB for any [file:<id>] refs in the
  /// current messages, then calls [expandFileRefs].
  Future<List<Message>> _expandMessages(List<Message> messages) async {
    final fileIds = <String>[];
    final refRegex = RegExp(r'\[file:([^\]]+)\]');
    for (final m in messages) {
      if (m.role != MessageRole.user) continue;
      for (final match in refRegex.allMatches(m.content)) {
        fileIds.add(match.group(1)!);
      }
    }
    if (fileIds.isEmpty) return messages;
    final descriptions = <String, String>{};
    for (final id in fileIds) {
      final desc = await _fileStore?.descriptionFor(id);
      if (desc != null && desc.trim().isNotEmpty) {
        descriptions[id] = desc;
      }
    }
    return expandFileRefs(messages, descriptions);
  }

  Future<void> retry() async {
    final current = state.value;
    if (current == null || current.isStreaming) return;
    final failedId = current.failedMessageId;
    final lastText = _lastUserText;
    if (failedId == null || lastText == null) return;

    // Drop the failed assistant placeholder from the store too, so the retried
    // turn doesn't leave a stale partial assistant message persisted next to
    // the successful one.
    await _store!.deleteMessage(conversationId, failedId);
    if (!ref.mounted) return;

    // Drop the failed assistant placeholder from in-memory state and re-run
    // the last send.
    _setState(current.copyWith(
      messages: [
        for (final m in current.messages)
          if (m.id != failedId) m,
      ],
      isStreaming: true,
      error: null,
      failedMessageId: null,
    ));

    await _runTurn();
  }

  Future<void> stop() async {
    _active?.cancel();
    _active = null;
    _throttle?.cancel();
    _throttle = null;
    // Flush any coalesced content, then read the updated state so the partial
    // content is retained when streaming flags are cleared below.
    _flushThrottle();
    final current = state.value;
    if (current == null) return;
    _setState(current.copyWith(
      isStreaming: false,
      pendingUserMessageId: null,
    ));
    // Persist whatever partial content exists.
    final pendingId = _pendingAssistantId;
    if (pendingId != null && ref.mounted) {
      final messages = state.value?.messages ?? const <Message>[];
      final partial = messages.where((m) => m.id == pendingId).toList();
      if (partial.isNotEmpty) {
        await _store!.updateMessage(conversationId, partial.first);
      }
    }
    _pendingAssistantId = null;
    _pendingContent = null;
  }

  Future<void> clear() async {
    final current = state.value;
    if (current == null) return;
    _setState(current.copyWith(messages: const []));
  }

  /// Runs one or more streaming turns, dispatching tools between calls.
  Future<void> _runTurn() async {
    final token = CancelToken();
    _active = token;
    try {
      await _streamOnce(token);
    } finally {
      _active = null;
      _throttle?.cancel();
      _throttle = null;
      _flushThrottle();
    }
  }

  Future<void> _streamOnce(CancelToken token) async {
    for (var toolIteration = 0; toolIteration < 5; toolIteration++) {
      if (!ref.mounted) return;
      final current = state.value;
      if (current == null) return;

      // Rebuild API messages from the current state each iteration so the
      // assistant tool_calls + tool results are included after dispatch. The
      // in-flight assistant placeholder is NOT part of the request history.
      // Expand [file:<id>] refs into [Image: ...] descriptions BEFORE trim,
      // so the injected description text is counted within the token budget.
      final expandedMessages = await _expandMessages(current.messages);
      final trimmed = _trimmer!.trim(expandedMessages);
      final messagesForCall = toApiMessages(trimmed);

      // Fresh assistant placeholder per turn, so tool-loop iterations each get
      // their own message to stream into.
      final assistant = Message(
        id: _uuid.v4(),
        role: MessageRole.assistant,
        content: '',
        createdAt: DateTime.now(),
      );
      _pendingAssistantId = assistant.id;
      _pendingContent = StringBuffer();

      _setState(current.copyWith(
        messages: [...current.messages, assistant],
      ));

      ChatResult result;
      try {
        result = await _client!.streamCompletions(
          messages: messagesForCall,
          systemPrompt: kSystemPrompt,
          tools: _registry!.toolDefinitions,
          onContent: (text) => _onContent(assistant.id, text),
          cancelToken: token,
        );
      } catch (e) {
        await _onError(e, assistant.id, token);
        return;
      }
      if (!ref.mounted) return;

      final hasToolCalls = result.toolCalls.isNotEmpty;

      // Push any coalesced streaming content into state before finalizing.
      _flushThrottle();

      var finalized = assistant.copyWith(content: result.content);
      if (hasToolCalls) {
        finalized = finalized.copyWith(toolCalls: result.toolCalls);
      }
      await _store!.updateMessage(conversationId, finalized);
      if (!ref.mounted) return;

      final messages = [
        for (final m in state.value!.messages)
          if (m.id == assistant.id) finalized else m,
      ];
      _setState(state.value!.copyWith(messages: messages));

      if (!hasToolCalls) {
        // Done: 'stop' (or any non-tool finish).
        _setState(state.value!.copyWith(
          isStreaming: false,
          pendingUserMessageId: null,
          error: null,
          failedMessageId: null,
        ));
        _pendingAssistantId = null;
        _pendingContent = null;
        return;
      }

      // Execute tools sequentially and feed results back.
      for (final call in result.toolCalls) {
        final toolResult =
            await _registry!.dispatch(call.name, call.args ?? const {});
        if (!ref.mounted) return;
        final toolMsg = Message(
          id: _uuid.v4(),
          role: MessageRole.tool,
          content: toolResult.message,
          toolCallId: call.id,
          createdAt: DateTime.now(),
        );
        final cur = state.value!;
        await _store!.appendMessage(conversationId, toolMsg);
        if (!ref.mounted) return;
        _setState(cur.copyWith(messages: [...cur.messages, toolMsg]));
      }

      // Re-enter the loop with the now-longer history to request the model's
      // next turn. Cap the tool loop to avoid runaway tool chaining.
      if (toolIteration == 4) {
        final cap = Message(
          id: _uuid.v4(),
          role: MessageRole.assistant,
          content: 'Reached the tool-call limit',
          createdAt: DateTime.now(),
        );
        await _store!.appendMessage(conversationId, cap);
        if (!ref.mounted) return;
        _setState(state.value!.copyWith(
          messages: [...state.value!.messages, cap],
          isStreaming: false,
          pendingUserMessageId: null,
          error: null,
          failedMessageId: null,
        ));
        _pendingAssistantId = null;
        _pendingContent = null;
        return;
      }
    }
  }

  void _onContent(String assistantId, String text) {
    _pendingContent?.write(text);
    final existing = _throttle;
    if (existing != null) return;
    _throttle = Timer(const Duration(milliseconds: 80), () {
      _throttle = null;
      _flushThrottle();
    });
  }

  void _flushThrottle() {
    final id = _pendingAssistantId;
    final buffer = _pendingContent;
    if (id == null || buffer == null || !ref.mounted) return;
    final cur = state.value;
    if (cur == null) return;
    final content = buffer.toString();
    final updated = [
      for (final m in cur.messages)
        if (m.id == id) m.copyWith(content: content) else m,
    ];
    _setState(cur.copyWith(messages: updated));
  }

  String _assistantContent(String assistantId) {
    final cur = state.value;
    if (cur == null) return '';
    for (final m in cur.messages) {
      if (m.id == assistantId) {
        if (m.content.isNotEmpty) return m.content;
        // Streaming content lives in the coalescing buffer until the next
        // throttle flush; fall back to it so finalization keeps the partials.
        return _pendingContent?.toString() ?? '';
      }
    }
    return _pendingContent?.toString() ?? '';
  }

  Future<void> _onError(Object error, String assistantId, CancelToken token) async {
    if (!ref.mounted) return;
    final cur = state.value;
    if (cur == null) return;

    // A user-initiated stop cancels the token; a cancellation error from the
    // CURRENT token is suppressed (the partial content stays in place). Errors
    // from a stale, already-stopped turn are also suppressed via the token's
    // own cancelled state, so they can't be mis-attributed to a newer turn.
    if (token.isCancelled) {
      _pendingAssistantId = null;
      _pendingContent = null;
      return;
    }

    final message = switch (error) {
      ChatNetworkError(:final message) => message,
      ChatApiError(:final message) => message,
      DioException() => 'Network error',
      _ => 'Unexpected error',
    };

    if (error is ChatNetworkError || error is DioException) {
      ref.read(networkStatusProvider.notifier).set(NetworkStatus.disconnected);
    }

    // Keep partial content; persist it.
    final partialContent = _assistantContent(assistantId);
    final updated = <Message>[];
    var hasAssistant = false;
    for (final m in cur.messages) {
      if (m.id == assistantId) {
        hasAssistant = true;
        updated.add(m.copyWith(content: partialContent));
      } else {
        updated.add(m);
      }
    }
    var messages = updated;
    if (!hasAssistant) {
      messages = [
        ...messages,
        Message(
          id: assistantId,
          role: MessageRole.assistant,
          content: partialContent,
          createdAt: DateTime.now(),
        ),
      ];
    }

    await _store!.updateMessage(conversationId,
        messages.firstWhere((m) => m.id == assistantId));
    if (!ref.mounted) return;

    _setState(cur.copyWith(
      messages: messages,
      isStreaming: false,
      error: message,
      pendingUserMessageId: null,
      failedMessageId: assistantId,
    ));
    _pendingAssistantId = null;
    _pendingContent = null;
  }

  void _setState(ConversationState next) {
    if (!ref.mounted) return;
    state = AsyncData(next);
  }
}

/// Provides the [ContextTrimmer] used to enforce the token budget.
final contextTrimmerProvider = Provider<ContextTrimmer>(
  (ref) => const ContextTrimmer(),
);

/// Provides the default [ToolRegistry].
final toolRegistryProvider = Provider<ToolRegistry>(
  (ref) => buildDefaultToolRegistry(),
);

/// Fires when the underlying database is ready (via the chat store provider).
final databaseReadyProvider = Provider<Future<void>>(
  (ref) async {
    await ref.watch(chatStoreProvider).watchConversations().first;
  },
);

/// State notifier for a single conversation, keyed by conversation id.
final conversationProvider =
    AsyncNotifierProvider.autoDispose
        .family<ConversationNotifier, ConversationState, String>(
          ConversationNotifier.new,
        );

/// Stream of all conversations, ordered most-recently-updated first.
final conversationsProvider = StreamProvider.autoDispose<List<Conversation>>(
  (ref) => ref.watch(chatStoreProvider).watchConversations(),
);
